"""Person Vault field registry (C / I / E priorities)."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

CATALOG_VERSION = "1.4.0"
AUTH_PROVIDER_NAME = "supabase"
# Always-on scopes so PAI can see what a student still needs for guidance.
GUIDANCE_SCOPES = ("universal", "education", "application", "career")

Priority = Literal["C", "I", "E"]
Scope = Literal[
    "universal",
    "education",
    "career",
    "mobility",
    "finance",
    "application",
    "lifestyle",
]
StorageKind = Literal[
    "vault_value",
    "person",
    "educations",
    "work_experiences",
    "projects",
    "skills",
    "certifications",
    "goals",
]
ValueType = Literal["string", "number", "boolean", "date", "json", "array"]


@dataclass(frozen=True, slots=True)
class CatalogField:
    key: str
    section: str
    priority: Priority
    sensitive: bool
    derived: bool
    storage: StorageKind
    applicable_scope: Scope
    value_type: ValueType
    editable: bool
    repeatable: bool
    person_column: str | None = None
    consent_category: str | None = None


def _fields() -> tuple[CatalogField, ...]:
    return (
        # Auth-derived (sparse vault, not editable)
        CatalogField(
            key="auth.user_id",
            section="auth",
            priority="C",
            sensitive=False,
            derived=True,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=False,
            repeatable=False,
        ),
        CatalogField(
            key="auth.email",
            section="auth",
            priority="C",
            sensitive=False,
            derived=True,
            storage="person",
            applicable_scope="universal",
            value_type="string",
            editable=False,
            repeatable=False,
            person_column="email",
        ),
        CatalogField(
            key="auth.email_verified",
            section="auth",
            priority="C",
            sensitive=False,
            derived=True,
            storage="person",
            applicable_scope="universal",
            value_type="boolean",
            editable=False,
            repeatable=False,
            person_column="email_verified",
        ),
        CatalogField(
            key="auth.account_status",
            section="auth",
            priority="C",
            sensitive=False,
            derived=True,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=False,
            repeatable=False,
        ),
        # Person identity (typed on persons table)
        CatalogField(
            key="identity.full_name",
            section="identity",
            priority="C",
            sensitive=False,
            derived=False,
            storage="person",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
            person_column="full_name",
        ),
        CatalogField(
            key="identity.preferred_name",
            section="identity",
            priority="I",
            sensitive=False,
            derived=False,
            storage="person",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
            person_column="preferred_name",
        ),
        CatalogField(
            key="identity.phone",
            section="identity",
            priority="C",
            sensitive=False,
            derived=False,
            storage="person",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
            person_column="phone",
        ),
        CatalogField(
            key="identity.current_status",
            section="identity",
            priority="C",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="identity.national_id",
            section="identity",
            priority="I",
            sensitive=True,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
            consent_category="identity",
        ),
        CatalogField(
            key="demographics.gender",
            section="demographics",
            priority="C",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="demographics.nationality",
            section="demographics",
            priority="C",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="social.linkedin_url",
            section="social",
            priority="E",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="education.highest_level",
            section="education",
            priority="C",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="education",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        # Sparse preferences
        CatalogField(
            key="preferences.preferred_language",
            section="preferences",
            priority="I",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="preferences.communication_style",
            section="preferences",
            priority="E",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="preferences.learning_style",
            section="preferences",
            priority="E",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        # Typed section presence (completion probes)
        CatalogField(
            key="education.records",
            section="education",
            priority="C",
            sensitive=False,
            derived=True,
            storage="educations",
            applicable_scope="education",
            value_type="json",
            editable=False,
            repeatable=True,
        ),
        CatalogField(
            key="education.program",
            section="education",
            priority="C",
            sensitive=False,
            derived=False,
            storage="educations",
            applicable_scope="education",
            value_type="json",
            editable=True,
            repeatable=True,
        ),
        CatalogField(
            key="education.gpa",
            section="education",
            priority="C",
            sensitive=False,
            derived=False,
            storage="educations",
            applicable_scope="education",
            value_type="json",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="career.work_history",
            section="career",
            priority="C",
            sensitive=False,
            derived=False,
            storage="work_experiences",
            applicable_scope="career",
            value_type="json",
            editable=True,
            repeatable=True,
        ),
        CatalogField(
            key="career.projects",
            section="career",
            priority="I",
            sensitive=False,
            derived=False,
            storage="projects",
            applicable_scope="career",
            value_type="json",
            editable=True,
            repeatable=True,
        ),
        CatalogField(
            key="career.skills",
            section="career",
            priority="C",
            sensitive=False,
            derived=False,
            storage="skills",
            applicable_scope="career",
            value_type="json",
            editable=True,
            repeatable=True,
        ),
        CatalogField(
            key="career.certifications",
            section="career",
            priority="I",
            sensitive=False,
            derived=False,
            storage="certifications",
            applicable_scope="career",
            value_type="json",
            editable=True,
            repeatable=True,
        ),
        CatalogField(
            key="application.goals",
            section="application",
            priority="I",
            sensitive=False,
            derived=True,
            storage="goals",
            applicable_scope="application",
            value_type="json",
            editable=False,
            repeatable=True,
        ),
        CatalogField(
            key="application.career_interest",
            section="application",
            priority="I",
            sensitive=False,
            derived=False,
            storage="goals",
            applicable_scope="application",
            value_type="string",
            editable=True,
            repeatable=True,
        ),
        # Admissions / PK counseling sparse fields (vault_value — no fabricated typed rows)
        CatalogField(
            key="education.stream",
            section="education",
            priority="I",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="education",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="education.marks",
            section="education",
            priority="I",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="education",
            value_type="json",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="education.additional_maths",
            section="education",
            priority="I",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="education",
            value_type="boolean",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="location.current_country",
            section="location",
            priority="C",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="location.current_city",
            section="location",
            priority="C",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="application.study_country",
            section="application",
            priority="C",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="application",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="application.target_universities",
            section="application",
            priority="I",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="application",
            value_type="array",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="application.admission_cycle",
            section="application",
            priority="I",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="application",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="application.test_scores",
            section="application",
            priority="I",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="application",
            value_type="array",
            editable=True,
            repeatable=False,
        ),
        # Mobility / finance / lifestyle sparse
        CatalogField(
            key="mobility.passport_number",
            section="mobility",
            priority="C",
            sensitive=True,
            derived=False,
            storage="vault_value",
            applicable_scope="mobility",
            value_type="string",
            editable=True,
            repeatable=False,
            consent_category="mobility",
        ),
        CatalogField(
            key="mobility.relocation_willingness",
            section="mobility",
            priority="I",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="mobility",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="mobility.preferred_regions",
            section="mobility",
            priority="E",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="mobility",
            value_type="array",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="finance.funding_status",
            section="finance",
            priority="I",
            sensitive=True,
            derived=False,
            storage="vault_value",
            applicable_scope="finance",
            value_type="string",
            editable=True,
            repeatable=False,
            consent_category="finance",
        ),
        CatalogField(
            key="finance.scholarship_interest",
            section="finance",
            priority="E",
            sensitive=True,
            derived=False,
            storage="vault_value",
            applicable_scope="finance",
            value_type="boolean",
            editable=True,
            repeatable=False,
            consent_category="finance",
        ),
        CatalogField(
            key="lifestyle.work_life_balance",
            section="lifestyle",
            priority="E",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="lifestyle",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="accessibility.accommodation_needs",
            section="accessibility",
            priority="I",
            sensitive=True,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
            consent_category="accessibility",
        ),
        CatalogField(
            key="demographics.date_of_birth",
            section="demographics",
            priority="C",
            sensitive=True,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="date",
            editable=True,
            repeatable=False,
            consent_category="demographics",
        ),
        CatalogField(
            key="family.sponsor_contact",
            section="family",
            priority="E",
            sensitive=True,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="json",
            editable=True,
            repeatable=False,
            consent_category="family",
        ),
    )


VAULT_CATALOG: dict[str, CatalogField] = {f.key: f for f in _fields()}


def get_catalog_field(key: str) -> CatalogField | None:
    return VAULT_CATALOG.get(key)


def extraction_catalog_hint() -> str:
    """Compact writable field list for the fact-extraction LLM (exact keys only)."""
    lines = [
        "Allowed field_key values (use exactly). If none fit, use memory.observed:",
        "",
        "Education typed JSON (prefer education.program):",
        '  education.program → {"institution"?, "degree", "major"/"stream", "gpa"?, '
        '"percentage"?, "marks_obtained"?, "marks_total"?, "graduation_year"?}',
        "  education.gpa → same JSON shape when updating GPA/marks on an education row",
        "  education.stream → string as named (IB, A-Levels, FSc Pre-Medical, AP, …)",
        '  education.marks → {"obtained": 877, "total": 1100} or "877/1100"',
        "  education.additional_maths → true|false",
        "  education.highest_level → high_school | diploma | bachelor | master | phd | other",
        "",
        "Career typed JSON (one candidate per item, or a list):",
        '  career.work_history → {"organization","title","employment_type"?,'
        '"is_current"?,"description"?,"start_date"?,"end_date"?}',
        '  career.skills → {"name","proficiency"?} or a skill name string',
        '  career.projects → {"name","role"?,"description"?,"url"?}',
        '  career.certifications → {"name","issuer"?}',
        "",
        "Goals / admissions:",
        "  application.career_interest → string program/goal as stated (e.g. MS AI in Germany)",
        "  application.study_country → string (ISO name or code as given)",
        "  application.target_universities → institution names the student named",
        "  application.admission_cycle → string",
        '  application.test_scores → [{"name":"ielts","score":"7.5"}, ...]',
        "",
        "Identity / location / other writable keys:",
    ]
    skip_prefix = ("education.", "application.", "career.")
    for f in sorted(VAULT_CATALOG.values(), key=lambda x: x.key):
        if f.derived or not f.editable:
            continue
        if f.key.startswith(skip_prefix):
            continue
        lines.append(f"  {f.key} ({f.value_type})")
    lines.extend(
        [
            "",
            "Escape hatch (not a Vault write — keep the fact, do not drop it):",
            '  memory.observed → short string; set fact_type=OTHER_POTENTIAL_FACT',
        ]
    )
    return "\n".join(lines)
